# Generated by Django 5.1.3 on 2026-01-14 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaeducativo',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
