# Generated by Django 5.1.3 on 2026-02-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0003_programaeducativo_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='estado',
        ),
    ]
