# Generated by Django 5.1.3 on 2026-02-24 03:06

import core.utils.file_helpers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0004_remove_inscripcion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialmodulos',
            name='path',
        ),
        migrations.RemoveField(
            model_name='materialmodulos',
            name='storage_name',
        ),
        migrations.AddField(
            model_name='materialmodulos',
            name='checksum',
            field=models.CharField(blank=True, editable=False, help_text='Hash del archivo para verificar integridad', max_length=64, verbose_name='Checksum (SHA256)'),
        ),
        migrations.AddField(
            model_name='materialmodulos',
            name='file',
            field=models.FileField(blank=True, help_text='Archivo físico almacenado', max_length=500, null=True, upload_to=core.utils.file_helpers.generic_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='materialmodulos',
            name='file_type',
            field=models.CharField(choices=[('document', 'Documento'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('spreadsheet', 'Hoja de cálculo'), ('presentation', 'Presentación'), ('archive', 'Archivo comprimido'), ('other', 'Otro')], db_index=True, default='other', help_text='Categoría del archivo detectada automáticamente', max_length=20, verbose_name='Tipo de archivo'),
        ),
        migrations.AlterField(
            model_name='materialmodulos',
            name='mime_type',
            field=models.CharField(blank=True, help_text='Tipo MIME detectado automáticamente', max_length=100, verbose_name='Tipo MIME'),
        ),
        migrations.AlterField(
            model_name='materialmodulos',
            name='original_name',
            field=models.CharField(help_text='Nombre original del archivo al momento de subirlo', max_length=500, verbose_name='Nombre original'),
        ),
        migrations.AlterField(
            model_name='materialmodulos',
            name='size',
            field=models.BigIntegerField(default=0, help_text='Tamaño del archivo en bytes', verbose_name='Tamaño (bytes)'),
        ),
        migrations.AlterField(
            model_name='materialmodulos',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddIndex(
            model_name='materialmodulos',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='control_esc_uploade_396e36_idx'),
        ),
    ]
