# Generated by Django 5.1.3 on 2026-02-24 04:52

import core.utils.file_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0005_remove_materialmodulos_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmodulos',
            name='file',
            field=models.FileField(help_text='Archivo físico almacenado', max_length=500, upload_to=core.utils.file_helpers.generic_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='materialmodulos',
            name='original_name',
            field=models.CharField(blank=True, help_text='Nombre original del archivo al momento de subirlo', max_length=500, null=True, verbose_name='Nombre original'),
        ),
    ]
