# Generated by Django 5.1.3 on 2026-02-27 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0006_alter_materialmodulos_file_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='plan_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.planpago'),
        ),
    ]
