from .programas_educativos import ProgramaEductiavoModelViewSet, ProgramaEducativoGenericoView
from .alumnos import EstudiantePerfilViewSet
from .campanias import CampaniaModelViewSet
from .pago import TipoPagoView