# Generated by Django 5.1.3 on 2026-01-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_initial'),
        ('user', '0003_alter_role_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='Localidad',
        ),
    ]
