# Generated by Django 5.1.3 on 2026-02-27 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_rename_ciudad_localidad'),
        ('control_escolar', '0007_inscripcion_plan_pago'),
        ('crm', '0001_initial'),
        ('sistema', '0002_modulo_uuid_pestania_uuid'),
        ('user', '0004_estudianteperfil_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='planpago',
            old_name='documentacion_propuesta',
            new_name='documentacion_monto',
        ),
        migrations.RenameField(
            model_name='planpago',
            old_name='inscripcion_propuesta',
            new_name='inscripcion_monto',
        ),
        migrations.RenameField(
            model_name='planpago',
            old_name='mensualidad_propuesta',
            new_name='mensualidad_monto',
        ),
        migrations.RemoveField(
            model_name='planpago',
            name='porcentaje_descuento',
        ),
        migrations.AddField(
            model_name='planpago',
            name='estudiante_existente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudiante_perfil', to='user.estudianteperfil'),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='campania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_pagos', to='control_escolar.campania'),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='crm.lead'),
        ),
        migrations.CreateModel(
            name='EstadoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=50)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='sistema.empresa')),
                ('instituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_instituto', to='catalogos.institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planpago',
            name='estado_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_estado', to='crm.estadoplan'),
        ),
        migrations.CreateModel(
            name='OrigenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=50)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_empresa', to='sistema.empresa')),
                ('instituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_instituto', to='catalogos.institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planpago',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_origen', to='crm.origenpago'),
        ),
    ]
