# Generated by Django 5.1.3 on 2026-01-14 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_role_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteperfil',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
